import {
  Activity,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Baby,
  Bell,
  BellRing,
  Brain,
  Briefcase,
  CalendarDays,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronUp,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CircleQuestionMark,
  Clock,
  Cloud,
  CloudDrizzle,
  CloudFog,
  CloudLightning,
  CloudRain,
  CloudRainWind,
  CloudSun,
  Cloudy,
  Compass,
  CopyX,
  Cpu,
  Database,
  Dot,
  Droplet,
  Droplets,
  ExternalLink,
  Eye,
  FaceSlightlySmiling,
  Flame,
  Flower,
  Footprints,
  Gauge,
  GlassWater,
  HardDrive,
  HeartPulse,
  Info,
  Layers,
  LayoutDashboard,
  LayoutGrid,
  Leaf,
  Lightbulb,
  List,
  ListChecks,
  LogOut,
  Map,
  MapPin,
  MapPinned,
  Moon,
  PanelRightClose,
  PanelRightOpen,
  Plane,
  Play,
  Plus,
  Radio,
  RefreshCw,
  RotateCw,
  Ruler,
  ScanEye,
  School,
  Search,
  SearchCheck,
  Send,
  Settings,
  ShieldAlert,
  ShieldCheck,
  Shuffle,
  SlidersHorizontal,
  Snowflake,
  Sparkles,
  SprayCan,
  Sprout,
  Stethoscope,
  Sun,
  SunMedium,
  SunMoon,
  Sunrise,
  Sunset,
  Text,
  Thermometer,
  ThermometerSun,
  Timer,
  TrendingUp,
  TriangleAlert,
  Umbrella,
  Unplug,
  UserRound,
  Users,
  Wind,
  X,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

/**
 * Static registry: lucide-react is tree-shaken, so icon names coming from JSON
 * are resolved through this map. Unknown names render a neutral info glyph.
 */
const registry: Record<string, LucideIcon> = {
  activity: Activity,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'arrow-up-right': ArrowUpRight,
  baby: Baby,
  bell: Bell,
  'bell-ring': BellRing,
  brain: Brain,
  briefcase: Briefcase,
  'calendar-days': CalendarDays,
  'chart-line': ChartLine,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-question-mark': CircleQuestionMark,
  clock: Clock,
  cloud: Cloud,
  'cloud-drizzle': CloudDrizzle,
  'cloud-fog': CloudFog,
  'cloud-lightning': CloudLightning,
  'cloud-rain': CloudRain,
  'cloud-rain-wind': CloudRainWind,
  'cloud-sun': CloudSun,
  cloudy: Cloudy,
  compass: Compass,
  'copy-x': CopyX,
  cpu: Cpu,
  database: Database,
  dot: Dot,
  droplet: Droplet,
  droplets: Droplets,
  'external-link': ExternalLink,
  eye: Eye,
  'face-slightly-smiling': FaceSlightlySmiling,
  flame: Flame,
  flower: Flower,
  footprints: Footprints,
  gauge: Gauge,
  'glass-water': GlassWater,
  'hard-drive': HardDrive,
  'heart-pulse': HeartPulse,
  info: Info,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  'layout-grid': LayoutGrid,
  leaf: Leaf,
  lightbulb: Lightbulb,
  list: List,
  'list-checks': ListChecks,
  'log-out': LogOut,
  map: Map,
  'map-pin': MapPin,
  'map-pinned': MapPinned,
  moon: Moon,
  'panel-right-close': PanelRightClose,
  'panel-right-open': PanelRightOpen,
  plane: Plane,
  play: Play,
  plus: Plus,
  radio: Radio,
  'refresh-cw': RefreshCw,
  'rotate-cw': RotateCw,
  ruler: Ruler,
  'scan-eye': ScanEye,
  school: School,
  search: Search,
  'search-check': SearchCheck,
  send: Send,
  settings: Settings,
  'shield-alert': ShieldAlert,
  'shield-check': ShieldCheck,
  shuffle: Shuffle,
  'sliders-horizontal': SlidersHorizontal,
  snowflake: Snowflake,
  sparkles: Sparkles,
  'spray-can': SprayCan,
  sprout: Sprout,
  stethoscope: Stethoscope,
  sun: Sun,
  'sun-high': SunMedium,
  'sun-medium': SunMedium,
  'sun-moon': SunMoon,
  sunrise: Sunrise,
  sunset: Sunset,
  text: Text,
  thermometer: Thermometer,
  'thermometer-sun': ThermometerSun,
  timer: Timer,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  umbrella: Umbrella,
  unplug: Unplug,
  'user-round': UserRound,
  users: Users,
  wind: Wind,
  x: X,
  zap: Zap,
}

export type IconProps = {
  name: string
  size?: number
  strokeWidth?: number
  className?: string
  color?: string
}

export const Icon = ({ name, size = 18, strokeWidth = 2, className, color }: IconProps) => {
  const Glyph = registry[name] ?? Info
  return <Glyph size={size} strokeWidth={strokeWidth} className={className} color={color} aria-hidden="true" />
}

export const hasIcon = (name: string) => Boolean(registry[name])
